### ISSUE TITLE
[FE] 첫 배포 버그 체크

### ISSUE THREAD

**Issue by healtheloper** [ikjo93/issue-tracker#65]
- [x] #66
- [x] #68
- [x] #75
- [x] #77
- [x] #69
- [x] #72
- [x] #73
- [x] #74

**Comment by happyGyu** [comment]
진행 중인 것은 convert to issue하고 담당자를 지정하겠습니다! 추가로 발견하는 버그는 여기에 추가하거나 다른 이슈를 하나 더 만들겠습니다.
